/**
 * @Summary: short description for the file
 * @Date: 2020/6/18 1:33 PM
 * @Author: Youth
 */
const area_pool = [
  {
    pool_channel: 'topn_taiwan_pool',
    channel: '台湾地方站',
    channel_name: 'news_news_antip',
    topn: 'pneumonia_topn_taiwan_pool',
    topn_name: '肺炎池_台湾地方站',
    type: '地方站',
    name: 'taiwan',
    area: '台湾'
  },
  {
    pool_channel: 'topn_macau_pool',
    channel: '澳门地方站',
    channel_name: 'news_news_antip',
    topn: 'pneumonia_topn_macau_pool',
    topn_name: '肺炎池_澳门地方站',
    type: '地方站',
    name: 'macau',
    area: '澳门'
  },
  {
    pool_channel: 'topn_hk_pool',
    channel: '香港地方站',
    channel_name: 'news_news_antip',
    topn: 'pneumonia_topn_hk_pool',
    topn_name: '肺炎池_香港地方站',
    type: '地方站',
    name: 'hk',
    area: '香港'
  },
  {
    pool_channel: 'cq_pool',
    channel: '重庆地方站',
    channel_name: 'news_news_cq',
    topn: 'pneumonia_cq_pool',
    topn_name: '肺炎池_重庆地方站',
    type: '地方站',
    name: 'cq',
    area: '重庆'
  },
  {
    pool_channel: 'zj_pool',
    channel: '浙江地方站',
    channel_name: 'news_news_zj',
    topn: 'pneumonia_zj_pool',
    topn_name: '肺炎池_浙江地方站',
    type: '地方站',
    name: 'zj',
    area: '浙江'
  },
  {
    pool_channel: 'yn_pool',
    channel: '云南地方站',
    channel_name: 'news_news_yn',
    topn: 'pneumonia_yn_pool',
    topn_name: '肺炎池_云南地方站',
    type: '地方站',
    name: 'yn',
    area: '云南'
  },
  {
    pool_channel: 'xinjiang_pool',
    channel: '新疆地方站',
    channel_name: 'news_news_xinjiang',
    topn: 'pneumonia_xinjiang_pool',
    topn_name: '肺炎池_新疆地方站',
    type: '地方站',
    name: 'xinjiang',
    area: '新疆'
  },
  {
    pool_channel: 'xizang_pool',
    channel: '西藏地方站',
    channel_name: 'news_news_xizang',
    topn: 'pneumonia_xizang_pool',
    topn_name: '肺炎池_西藏地方站',
    type: '地方站',
    name: 'xizang',
    area: '西藏'
  },
  {
    pool_channel: 'tj_pool',
    channel: '天津分站',
    channel_name: 'news_news_tj',
    topn: 'pneumonia_tj_pool',
    topn_name: '肺炎池_天津分站',
    type: '地方站',
    name: 'tj',
    area: '天津'
  },
  {
    pool_channel: 'cd_pool',
    channel: '四川地方站',
    channel_name: 'news_news_cd',
    topn: 'pneumonia_cd_pool',
    topn_name: '肺炎池_四川地方站',
    type: '地方站',
    name: 'cd',
    area: '四川'
  },
  {
    pool_channel: 'xian_pool',
    channel: '陕西地方站',
    channel_name: 'news_news_xian',
    topn: 'pneumonia_xian_pool',
    topn_name: '肺炎池_陕西地方站',
    type: '地方站',
    name: 'xian',
    area: '陕西'
  },
  {
    pool_channel: 'shanxi_pool',
    channel: '山西地方站',
    channel_name: 'news_news_shanxi',
    topn: 'pneumonia_shanxi_pool',
    topn_name: '肺炎池_山西地方站',
    type: '地方站',
    name: 'shanxi',
    area: '山西'
  },
  {
    pool_channel: 'qinghai_pool',
    channel: '青海地方站',
    channel_name: 'news_news_qinghai',
    topn: 'pneumonia_qinghai_pool',
    topn_name: '肺炎池_青海地方站',
    type: '地方站',
    name: 'qinghai',
    area: '青海'
  },
  {
    pool_channel: 'ningxia_pool',
    channel: '宁夏地方站',
    channel_name: 'news_news_ningxia',
    topn: 'pneumonia_ningxia_pool',
    topn_name: '肺炎池_宁夏地方站',
    type: '地方站',
    name: 'ningxia',
    area: '宁夏'
  },
  {
    pool_channel: 'neimenggu_pool',
    channel: '内蒙古地方站',
    channel_name: 'news_news_neimenggu',
    topn: 'pneumonia_neimenggu_pool',
    topn_name: '肺炎池_内蒙古地方站',
    type: '地方站',
    name: 'neimenggu',
    area: '内蒙古'
  },
  {
    pool_channel: 'ln_pool',
    channel: '辽宁地方站',
    channel_name: 'news_news_ln',
    topn: 'pneumonia_ln_pool',
    topn_name: '肺炎池_辽宁地方站',
    type: '地方站',
    name: 'ln',
    area: '辽宁'
  },
  {
    pool_channel: 'jiangxi_pool',
    channel: '江西地方站',
    channel_name: 'news_news_jiangxi',
    topn: 'pneumonia_jiangxi_pool',
    topn_name: '肺炎池_江西地方站',
    type: '地方站',
    name: 'jiangxi',
    area: '江西'
  },
  {
    pool_channel: 'jiangsu_pool',
    channel: '江苏地方站',
    channel_name: 'news_news_js',
    topn: 'pneumonia_jiangsu_pool',
    topn_name: '肺炎池_江苏地方站',
    type: '地方站',
    name: 'jiangsu',
    area: '江苏'
  },
  {
    pool_channel: 'jilin_pool',
    channel: '吉林省地方站',
    channel_name: 'news_news_jilin',
    topn: 'pneumonia_jilin_pool',
    topn_name: '肺炎池_吉林省地方站',
    type: '地方站',
    name: 'jilin',
    area: '吉林'
  },
  {
    pool_channel: 'hn_pool',
    channel: '湖南地方站',
    channel_name: 'news_news_hn',
    topn: 'pneumonia_hn_pool',
    topn_name: '肺炎池_湖南地方站',
    type: '地方站',
    name: 'hn',
    area: '湖南'
  },
  {
    pool_channel: 'heilongjiang_pool',
    channel: '黑龙江地方站',
    channel_name: 'news_news_heilongjiang',
    topn: 'pneumonia_heilongjiang_pool',
    topn_name: '肺炎池_黑龙江地方站',
    type: '地方站',
    name: 'heilongjiang',
    area: '黑龙江'
  },
  {
    pool_channel: 'henan_pool',
    channel: '河南地方站',
    channel_name: 'news_news_henan',
    topn: 'pneumonia_henan_pool',
    topn_name: '肺炎池_河南地方站',
    type: '地方站',
    name: 'henan',
    area: '河南'
  },
  {
    pool_channel: 'hebei_pool',
    channel: '河北分站',
    channel_name: 'news_news_heb',
    topn: 'pneumonia_hebei_pool',
    topn_name: '肺炎池_河北分站',
    type: '地方站',
    name: 'hebei',
    area: '河北'
  },
  {
    pool_channel: 'hainan_pool',
    channel: '海南地方站',
    channel_name: 'news_nwes_hainan',
    topn: 'pneumonia_hainan_pool',
    topn_name: '肺炎池_海南地方站',
    type: '地方站',
    name: 'hainan',
    area: '海南'
  },
  {
    pool_channel: 'guizhou_pool',
    channel: '贵州地方站',
    channel_name: 'news_news_guizhou',
    topn: 'pneumonia_guizhou_pool',
    topn_name: '肺炎池_贵州地方站',
    type: '地方站',
    name: 'guizhou',
    area: '贵州'
  },
  {
    pool_channel: 'guangxi_pool',
    channel: '广西地方站',
    channel_name: 'news_news_guangxi',
    topn: 'pneumonia_guangxi_pool',
    topn_name: '肺炎池_广西地方站',
    type: '地方站',
    name: 'guangxi',
    area: '广西'
  },
  {
    pool_channel: 'gd_pool',
    channel: '广东地方站',
    channel_name: 'news_news_gd',
    topn: 'pneumonia_gd_pool',
    topn_name: '肺炎池_广东地方站',
    type: '地方站',
    name: 'gd',
    area: '广东'
  },
  {
    pool_channel: 'gansu_pool',
    channel: '甘肃地方站',
    channel_name: 'news_news_gansu',
    topn: 'pneumonia_gansu_pool',
    topn_name: '肺炎池_甘肃地方站',
    type: '地方站',
    name: 'gansu',
    area: '甘肃'
  },
  {
    pool_channel: 'fj_pool',
    channel: '福建地方站',
    channel_name: 'news_news_fj',
    topn: 'pneumonia_fj_pool',
    topn_name: '肺炎池_福建地方站',
    type: '地方站',
    name: 'fj',
    area: '福建'
  },
  {
    pool_channel: 'ah_pool',
    channel: '安徽地方站',
    channel_name: 'news_news_anhui',
    topn: 'pneumonia_ah_pool',
    topn_name: '肺炎池_安徽地方站',
    type: '地方站',
    name: 'ah',
    area: '安徽'
  },
  {
    pool_channel: 'sh_pool',
    channel: '上海地方站',
    channel_name: 'news_news_sh',
    topn: 'pneumonia_sh_pool',
    topn_name: '肺炎池_上海地方站',
    type: '地方站',
    name: 'sh',
    area: '上海'
  },
  {
    pool_channel: 'bj_pool',
    channel: '北京分站',
    channel_name: 'news_news_bj',
    topn: 'pneumonia_bj_pool',
    topn_name: '肺炎池_北京分站',
    type: '地方站',
    name: 'bj',
    area: '北京'
  },
  {
    pool_channel: 'hb_pool',
    channel: '湖北地方站',
    channel_name: 'news_news_hb',
    topn: 'pneumonia_hb_pool',
    topn_name: '肺炎池_湖北地方站',
    type: '地方站',
    name: 'hb',
    area: '湖北'
  },
  {
    pool_channel: 'sd_pool',
    channel: '山东地方站',
    channel_name: 'news_news_sd',
    topn: 'pneumonia_sd_pool',
    topn_name: '肺炎池_山东地方站',
    type: '地方站',
    name: 'sd',
    area: '山东'
  }
];

const local_chllist = [
  {
    chlid: 'news_news_cq',
    chlname: '重庆',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '重庆',
    adcode: 500000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gd',
    chlname: '广东',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '广东',
    adcode: 440000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gz',
    chlname: '广州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 440100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sz',
    chlname: '深圳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 440300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shantou',
    chlname: '汕头',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 440500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_dg',
    chlname: '东莞',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 441900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_foshan',
    chlname: '佛山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 440600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jm',
    chlname: '江门',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 440700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zhanjiang',
    chlname: '湛江',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 440800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_huizhou',
    chlname: '惠州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 441300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zhongshan',
    chlname: '中山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 442000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jieyang',
    chlname: '揭阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 445200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdzh',
    chlname: '珠海',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 440400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdsg',
    chlname: '韶关',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 440200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdmm',
    chlname: '茂名',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 440900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdzq',
    chlname: '肇庆',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 441200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdmz',
    chlname: '梅州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 441400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdsw',
    chlname: '汕尾',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 441500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdhy',
    chlname: '河源',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 441600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdyj',
    chlname: '阳江',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 441700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdqy',
    chlname: '清远',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 441800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdcz',
    chlname: '潮州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 445100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gdyf',
    chlname: '云浮',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广东',
    adcode: 445300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_cd',
    chlname: '四川',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '四川',
    adcode: 510000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_chengdu',
    chlname: '成都',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 510100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_mianyang',
    chlname: '绵阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 510700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sczg',
    chlname: '自贡',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 510300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scpzh',
    chlname: '攀枝花',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 510400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sclz',
    chlname: '泸州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 510500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scdy',
    chlname: '德阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 510600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scgy',
    chlname: '广元',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 510800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scsn',
    chlname: '遂宁',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 510900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scnj',
    chlname: '内江',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 511000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scls',
    chlname: '乐山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 511100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scnc',
    chlname: '南充',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 511300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scms',
    chlname: '眉山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 511400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scyb',
    chlname: '宜宾',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 511500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scga',
    chlname: '广安',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 511600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scdz',
    chlname: '达州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 511700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scya',
    chlname: '雅安',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 511800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scbz',
    chlname: '巴中',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 511900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sczy',
    chlname: '资阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 512000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scab',
    chlname: '阿坝州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 513200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_scgz',
    chlname: '甘孜州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 513300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sclsz',
    chlname: '凉山州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '四川',
    adcode: 513400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sh',
    chlname: '上海',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '上海',
    adcode: 310000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xian',
    chlname: '陕西',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '陕西',
    adcode: 610000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shan3xi',
    chlname: '西安',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 610100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_yulin',
    chlname: '榆林',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 610800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xianyang',
    chlname: '咸阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 610400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sxtc',
    chlname: '铜川',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 610200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sxbj',
    chlname: '宝鸡',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 610300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sxwn',
    chlname: '渭南',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 610500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sxya',
    chlname: '延安',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 610600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sxhz',
    chlname: '汉中',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 610700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sxak',
    chlname: '安康',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 610900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sxal',
    chlname: '商洛',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '陕西',
    adcode: 611000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zj',
    chlname: '浙江',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '浙江',
    adcode: 330000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hz',
    chlname: '杭州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 330100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_wz',
    chlname: '温州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 330300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nb',
    chlname: '宁波',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 330200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zjjh',
    chlname: '金华',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 330700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zjhz',
    chlname: '湖州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 330500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zjsx',
    chlname: '绍兴',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 330600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zjjx',
    chlname: '嘉兴',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 330400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zjzhs',
    chlname: '舟山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 330900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zjqz',
    chlname: '衢州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 330800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zjtz',
    chlname: '台州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 331000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lishui',
    chlname: '丽水',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '浙江',
    adcode: 331100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hb',
    chlname: '湖北',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '湖北',
    adcode: 420000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_wuhan',
    chlname: '武汉',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 420100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubes',
    chlname: '恩施',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 422800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_yichang',
    chlname: '宜昌',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 420500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xiangyang',
    chlname: '襄阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 420600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xiaogan',
    chlname: '孝感',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 420900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jingzhou',
    chlname: '荆州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 421000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xianning',
    chlname: '咸宁',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 421200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubhs',
    chlname: '黄石',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 420200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubsy',
    chlname: '十堰',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 420300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubez',
    chlname: '鄂州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 420700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubjm',
    chlname: '荆门',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 420800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubhg',
    chlname: '黄冈',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 421100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubsz',
    chlname: '随州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 421300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubxt',
    chlname: '仙桃',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 429004,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubqj',
    chlname: '潜江',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 429005,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubtm',
    chlname: '天门',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 429006,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hubsnj',
    chlname: '神农架',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖北',
    adcode: 429021,
    channelType: 'local'
  },
  {
    chlid: 'news_news_henan',
    chlname: '河南',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '河南',
    adcode: 410000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zhengzhou',
    chlname: '郑州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 410100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_luoyang',
    chlname: '洛阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 410300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_anyang',
    chlname: '安阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 410500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nanyang',
    chlname: '南阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 411300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shangqiu',
    chlname: '商丘',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 411400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xinyang',
    chlname: '信阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 411500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zhoukou',
    chlname: '周口',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 411600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lochnkf',
    chlname: '开封',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 410200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnpds',
    chlname: '平顶山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 410400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnjz',
    chlname: '焦作',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 410800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnhb',
    chlname: '鹤壁',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 410600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnxx',
    chlname: '新乡',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 410700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnpy',
    chlname: '濮阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 410900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnxc',
    chlname: '许昌',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 411000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnlh',
    chlname: '漯河',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 411100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnsmx',
    chlname: '三门峡',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 411200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnzmd',
    chlname: '驻马店',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 411700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnjy',
    chlname: '济源',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河南',
    adcode: 419001,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hn',
    chlname: '湖南',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '湖南',
    adcode: 430000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_changsha',
    chlname: '长沙',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 430100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xiangtan',
    chlname: '湘潭',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 430300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hengyang',
    chlname: '衡阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 430400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_yueyang',
    chlname: '岳阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 430600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_changde',
    chlname: '常德',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 430700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_chenzhou',
    chlname: '郴州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 431000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_huaihua',
    chlname: '怀化',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 431200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shaoyang',
    chlname: '邵阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 430500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ld',
    chlname: '娄底',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 431300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hunzz',
    chlname: '株洲',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 430200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_news_hunzjj',
    chlname: '张家界',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 430800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hunyy',
    chlname: '益阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 430900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hunyz',
    chlname: '永州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 431100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hunxx',
    chlname: '湘西',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '湖南',
    adcode: 433100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fj',
    chlname: '福建',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '福建',
    adcode: 350000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fuzhou',
    chlname: '福州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '福建',
    adcode: 350100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_quanzhou',
    chlname: '泉州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '福建',
    adcode: 350500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fjxm',
    chlname: '厦门',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '福建',
    adcode: 350200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fjpt',
    chlname: '莆田',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '福建',
    adcode: 350300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fjsm',
    chlname: '三明',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '福建',
    adcode: 350400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fjzz',
    chlname: '漳州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '福建',
    adcode: 350600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fjnp',
    chlname: '南平',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '福建',
    adcode: 350700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fhly',
    chlname: '龙岩',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '福建',
    adcode: 350800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fjnd',
    chlname: '宁德',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '福建',
    adcode: 350900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_js',
    chlname: '江苏',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '江苏',
    adcode: 320000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nj',
    chlname: '南京',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 320100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jswx',
    chlname: '无锡',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 320200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xuzhou',
    chlname: '徐州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 320300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_changzhou',
    chlname: '常州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 320400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_suz',
    chlname: '苏州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 320500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nantong',
    chlname: '南通',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 320600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jslyg',
    chlname: '连云港',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 320700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jsha',
    chlname: '淮安',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 320800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jsyc',
    chlname: '盐城',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 320900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jsyz',
    chlname: '扬州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 321000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jszj',
    chlname: '镇江',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 321100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jstz',
    chlname: '泰州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 321200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jssq',
    chlname: '宿迁',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江苏',
    adcode: 321300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ln',
    chlname: '辽宁',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '辽宁',
    adcode: 210000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lndl',
    chlname: '大连',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 210200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shenyang',
    chlname: '沈阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 210100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_anshan',
    chlname: '鞍山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 210300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_fushun',
    chlname: '抚顺',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 210400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_dandong',
    chlname: '丹东',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 210600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jinzhou',
    chlname: '锦州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 210700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_yingkou',
    chlname: '营口',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 210800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_loclntl',
    chlname: '铁岭',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 211200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lnbx',
    chlname: '本溪',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 210500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lnfx',
    chlname: '阜新',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 210900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lnly',
    chlname: '辽阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 211000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lnpj',
    chlname: '盘锦',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 211100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lncy',
    chlname: '朝阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 211300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lnhld',
    chlname: '葫芦岛',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '辽宁',
    adcode: 211400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_bj',
    chlname: '北京',
    recommend: 2,
    order: 3,
    isProvince: 1,
    refresh: 1,
    group: '北京',
    adcode: 110000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_tj',
    chlname: '天津',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '天津',
    adcode: 120000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_heb',
    chlname: '河北',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '河北',
    adcode: 130000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shijiazhuang',
    chlname: '石家庄',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ts',
    chlname: '唐山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hd',
    chlname: '邯郸',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xingtai',
    chlname: '邢台',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_bd',
    chlname: '保定',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_zhangjiakou',
    chlname: '张家口',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_cangzhou',
    chlname: '沧州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_lf',
    chlname: '廊坊',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 131000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hs',
    chlname: '衡水',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 131100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_chengde',
    chlname: '承德',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xiongan',
    chlname: '雄安',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130638,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hbqhd',
    chlname: '秦皇岛',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '河北',
    adcode: 130300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sd',
    chlname: '山东',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '山东',
    adcode: 370000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdjinan',
    chlname: '济南',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 370100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdqd',
    chlname: '青岛',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 370200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdzb',
    chlname: '淄博',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 370300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdzz',
    chlname: '枣庄',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 370400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sddy',
    chlname: '东营',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 370500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdyt',
    chlname: '烟台',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 370600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdwf',
    chlname: '潍坊',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 370700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdjining',
    chlname: '济宁',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 370800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdta',
    chlname: '泰安',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 370900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdwh',
    chlname: '威海',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 371000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdrz',
    chlname: '日照',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 371100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdlw',
    chlname: '莱芜',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 371200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdly',
    chlname: '临沂',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 371300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sddz',
    chlname: '德州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 371400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdlc',
    chlname: '聊城',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 371500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdbz',
    chlname: '滨州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 371600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sdhz',
    chlname: '菏泽',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山东',
    adcode: 371700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_yn',
    chlname: '云南',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '云南',
    adcode: 530000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynkm',
    chlname: '昆明',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 530100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynqj',
    chlname: '曲靖',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 530300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynyx',
    chlname: '玉溪',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 530400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynbs',
    chlname: '保山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 530500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynzt',
    chlname: '昭通',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 530600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynlj',
    chlname: '丽江',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 530700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynpe',
    chlname: '普洱',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 530800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynlc',
    chlname: '临沧',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 530900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_yncx',
    chlname: '楚雄',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 532300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynhh',
    chlname: '红河',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 532500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynws',
    chlname: '文山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 532600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynxsbn',
    chlname: '西双版纳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 532800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_yndl',
    chlname: '大理',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 532900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_yndh',
    chlname: '德宏',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 533100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ynnj',
    chlname: '怒江',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 533300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_yndq',
    chlname: '迪庆',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '云南',
    adcode: 533400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shanxi',
    chlname: '山西',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '山西',
    adcode: 140000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_sxty',
    chlname: '太原',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 140100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxdt',
    chlname: '大同',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 140200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxyq',
    chlname: '阳泉',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 140300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxcz',
    chlname: '长治',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 140400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxjc',
    chlname: '晋城',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 140500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxsz',
    chlname: '朔州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 140600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxjz',
    chlname: '晋中',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 140700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxyc',
    chlname: '运城',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 140800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxxz',
    chlname: '忻州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 140900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxlf',
    chlname: '临汾',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 141000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_shxll',
    chlname: '吕梁',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '山西',
    adcode: 141100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jilin',
    chlname: '吉林',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '吉林',
    adcode: 220000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jlcc',
    chlname: '长春',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '吉林',
    adcode: 220100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jljl',
    chlname: '吉林市',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '吉林',
    adcode: 220200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jlsp',
    chlname: '四平',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '吉林',
    adcode: 220300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jlly',
    chlname: '辽源',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '吉林',
    adcode: 220400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jlth',
    chlname: '通化',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '吉林',
    adcode: 220500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jlbs',
    chlname: '白山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '吉林',
    adcode: 220600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jlsy',
    chlname: '松原',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '吉林',
    adcode: 220700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jlbc',
    chlname: '白城',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '吉林',
    adcode: 220800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jlyb',
    chlname: '延边',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '吉林',
    adcode: 222400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_guizhou',
    chlname: '贵州',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '贵州',
    adcode: 520000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gzgy',
    chlname: '贵阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '贵州',
    adcode: 520100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gzlps',
    chlname: '六盘水',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '贵州',
    adcode: 520200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gzzy',
    chlname: '遵义',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '贵州',
    adcode: 520300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gzas',
    chlname: '安顺',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '贵州',
    adcode: 520400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gzbj',
    chlname: '毕节',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '贵州',
    adcode: 520500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gztr',
    chlname: '铜仁',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '贵州',
    adcode: 520600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gzqxn',
    chlname: '黔西南',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '贵州',
    adcode: 522300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gzqdn',
    chlname: '黔东南',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '贵州',
    adcode: 522600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gzqn',
    chlname: '黔南',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '贵州',
    adcode: 522700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jiangxi',
    chlname: '江西',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '江西',
    adcode: 360000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxnc',
    chlname: '南昌',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 360100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxjdz',
    chlname: '景德镇',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 360200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxpx',
    chlname: '萍乡',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 360300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxjj',
    chlname: '九江',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 360400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxxy',
    chlname: '新余',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 360500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxyt',
    chlname: '鹰潭',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 360600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxgz',
    chlname: '赣州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 360700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxja',
    chlname: '吉安',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 360800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxyc',
    chlname: '宜春',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 360900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxfz',
    chlname: '抚州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 361000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_jxsr',
    chlname: '上饶',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '江西',
    adcode: 361100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_anhui',
    chlname: '安徽',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '安徽',
    adcode: 340000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahhf',
    chlname: '合肥',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 340100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahwh',
    chlname: '芜湖',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 340200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahbb',
    chlname: '蚌埠',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 340300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahhn',
    chlname: '淮南',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 340400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahmas',
    chlname: '马鞍山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 340500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahhb',
    chlname: '淮北',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 340600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahtl',
    chlname: '铜陵',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 340700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahaq',
    chlname: '安庆',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 340800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahhs',
    chlname: '黄山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 341000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahczz',
    chlname: '滁州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 341100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahfy',
    chlname: '阜阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 341200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahsz',
    chlname: '宿州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 341300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahla',
    chlname: '六安',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 341500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahhz',
    chlname: '亳州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 341600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahcz',
    chlname: '池州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 341700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ahxc',
    chlname: '宣城',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '安徽',
    adcode: 341800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_guangxi',
    chlname: '广西',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '广西',
    adcode: 450000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxnn',
    chlname: '南宁',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 450100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxlz',
    chlname: '柳州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 450200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxgl',
    chlname: '桂林',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 450300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxwz',
    chlname: '梧州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 450400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxbh',
    chlname: '北海',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 450500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxfcg',
    chlname: '防城港',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 450600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxqz',
    chlname: '钦州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 450700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxgg',
    chlname: '贵港',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 450800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxyl',
    chlname: '玉林',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 450900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxbs',
    chlname: '百色',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 451000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxhz',
    chlname: '贺州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 451100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxhc',
    chlname: '河池',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 451200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxlb',
    chlname: '来宾',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 451300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gxcz',
    chlname: '崇左',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '广西',
    adcode: 451400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xizang',
    chlname: '西藏',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '西藏',
    adcode: 540000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_xinjiang',
    chlname: '新疆',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '新疆',
    adcode: 650000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_qinghai',
    chlname: '青海',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '青海',
    adcode: 630000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_qhxn',
    chlname: '西宁',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '青海',
    adcode: 630100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_qhhd',
    chlname: '海东',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '青海',
    adcode: 630200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_qhhb',
    chlname: '海北',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '青海',
    adcode: 632200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_qhhnn',
    chlname: '黄南',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '青海',
    adcode: 632300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_qhhn',
    chlname: '海南州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '青海',
    adcode: 632500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_qhgl',
    chlname: '果洛',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '青海',
    adcode: 632600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_qhys',
    chlname: '玉树',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '青海',
    adcode: 632700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_qhhx',
    chlname: '海西',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '青海',
    adcode: 632800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gansu',
    chlname: '甘肃',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '甘肃',
    adcode: 620000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gslz',
    chlname: '兰州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 620100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsjyg',
    chlname: '嘉峪关',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 620200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsjc',
    chlname: '金昌',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 620300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsby',
    chlname: '白银',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 620400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsts',
    chlname: '天水',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 620500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsww',
    chlname: '武威',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 620600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gszy',
    chlname: '张掖',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 620700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gspl',
    chlname: '平凉',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 620800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsjq',
    chlname: '酒泉',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 620900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsqy',
    chlname: '庆阳',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 621000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsdx',
    chlname: '定西',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 621100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsln',
    chlname: '陇南',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 621200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gslx',
    chlname: '临夏',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 622900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_gsgn',
    chlname: '甘南',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '甘肃',
    adcode: 623000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_neimenggu',
    chlname: '内蒙古',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '内蒙古',
    adcode: 150000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hhht',
    chlname: '呼和浩特',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 150100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgbt',
    chlname: '包头',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 150200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgwh',
    chlname: '乌海',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 150300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgcf',
    chlname: '赤峰',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 150400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgtl',
    chlname: '通辽',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 150500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgeeds',
    chlname: '鄂尔多斯',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 150600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmghlbe',
    chlname: '呼伦贝尔',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 150700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgbyze',
    chlname: '巴彦淖尔',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 150800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgwlcb',
    chlname: '乌兰察布',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 150900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgxam',
    chlname: '兴安盟',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 152200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgxlglm',
    chlname: '锡林郭勒',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 152500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nmgalsm',
    chlname: '阿拉善盟',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '内蒙古',
    adcode: 152900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_heilongjiang',
    chlname: '黑龙江',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '黑龙江',
    adcode: 230000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljheb',
    chlname: '哈尔滨',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 230100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljqqhe',
    chlname: '齐齐哈尔',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 230200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljjx',
    chlname: '鸡西',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 230300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljhg',
    chlname: '鹤岗',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 230400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljsys',
    chlname: '双鸭山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 230500,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljdq',
    chlname: '大庆',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 230600,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljyc',
    chlname: '伊春',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 230700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljjms',
    chlname: '佳木斯',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 230800,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljqth',
    chlname: '七台河',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 230900,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljmdj',
    chlname: '牡丹江',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 231000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljhh',
    chlname: '黑河',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 231100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljsh',
    chlname: '绥化',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 231200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hljdxal',
    chlname: '大兴安岭',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '黑龙江',
    adcode: 232700,
    channelType: 'local'
  },
  {
    chlid: 'news_news_ningxia',
    chlname: '宁夏',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '宁夏',
    adcode: 640000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nxyc',
    chlname: '银川',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '宁夏',
    adcode: 640100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nxszs',
    chlname: '石嘴山',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '宁夏',
    adcode: 640200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nxwz',
    chlname: '吴忠',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '宁夏',
    adcode: 640300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nxgy',
    chlname: '固原',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '宁夏',
    adcode: 640400,
    channelType: 'local'
  },
  {
    chlid: 'news_news_nxzw',
    chlname: '中卫',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '宁夏',
    adcode: 640500,
    channelType: 'local'
  },
  {
    chlid: 'news_nwes_hainan',
    chlname: '海南',
    recommend: 0,
    order: 0,
    isProvince: 1,
    refresh: 1,
    group: '海南',
    adcode: 460000,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hnhk',
    chlname: '海口',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '海南',
    adcode: 460100,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hansy',
    chlname: '三亚',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '海南',
    adcode: 460200,
    channelType: 'local'
  },
  {
    chlid: 'news_news_hanss',
    chlname: '三沙',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '海南',
    adcode: 460300,
    channelType: 'local'
  },
  {
    chlid: 'news_news_handz',
    chlname: '儋州',
    recommend: 0,
    order: 0,
    isProvince: 0,
    refresh: 1,
    group: '海南',
    adcode: 460400,
    channelType: 'local'
  }
];

export default {
  area_pool,
  local_chllist
}